### ISSUE TITLE
Save the dolphines!!!

### ISSUE THREAD

**Issue by Pfeifenjoy** [Louuiissaa/safeandsound#1]
![dolphin-03](https://cloud.githubusercontent.com/assets/8148840/25658534/b952aa5a-3003-11e7-9ffc-a470e7ad030e.jpg)

**Comment by Louuiissaa** [comment]
![21b2d24e-450d-40e0-afc1-ef3d143c025e](https://cloud.githubusercontent.com/assets/15330224/25659050/2bed863c-3006-11e7-9783-b980f46869d1.jpg)

**Comment by Louuiissaa** [comment]
![dolphin-sushi-36648](https://cloud.githubusercontent.com/assets/15330224/25659113/83a09c02-3006-11e7-8def-ffb0783c84bb.jpg)

**Comment by Pfeifenjoy** [comment]
![giphy 3](https://cloud.githubusercontent.com/assets/8148840/25659202/00ba4224-3007-11e7-886d-7f75f877b1b0.gif)

**Comment by Louuiissaa** [comment]
![eat-all-the-fish](https://cloud.githubusercontent.com/assets/15330224/25659362/bb2d5574-3007-11e7-9eb3-b37e4f326def.jpg)

**Comment by Pfeifenjoy** [comment]
That's OK, because dolphins aren't fish 😂

**Comment by Louuiissaa** [comment]
![i-may-be-smiling-funny-dolphin-meme1](https://cloud.githubusercontent.com/assets/15330224/25659486/4c2c93a0-3008-11e7-93d7-ada0a6df88ff.jpg)

**Comment by Pfeifenjoy** [comment]
![giphy 2](https://cloud.githubusercontent.com/assets/8148840/25659522/706ee628-3008-11e7-98c5-56ce41a125b2.gif)

**Comment by Louuiissaa** [comment]
![maxresdefault](https://cloud.githubusercontent.com/assets/15330224/25659636/f97cd56a-3008-11e7-92b5-9b2b85c45ef3.jpg)

**Comment by Pfeifenjoy** [comment]
This isn't solved yet!!!
@Louuiissaa Please reopen

**Comment by Louuiissaa** [comment]
Nö @Pfeifenjoy
